" .vimrc by Alex Azzo

" Automatic reloading of vimrc
autocmd! bufwritepost .vimrc source %

" Better copy and paste
set pastetoggle=<F2>
set clipboard=unnamed

" Spaces instead of tabs
set tabstop=4 softtabstop=4 expandtab shiftwidth=4 smarttab
set autoindent smartindent

" Rebind <Leader> key
let mapleader = ","

" Rebind command ":" key
nnoremap ; :

" Wildmenu and status bar
set wildmenu
set wildmode=list:longest,full
set laststatus=2

" map sort function to key
vnoremap <Leader>s :sort<CR>

" easier moving of code blocks
vnoremap < <gv
vnoremap > >gv

" tab and split movement
map <Leader>v :vsp<CR>
map <Leader>h :sp<CR>
map <C-j> <c-w>j
map <C-k> <c-w>k
map <C-l> <c-w>l
map <C-h> <c-w>h

" set number lines and no visual/sound bell
set noeb vb t_vb=
"set nu

" allow mouse movements
set mouse=a

" disable swap files
set nobackup
set nowritebackup
set noswapfile

" various settings
set nocompatible
set showmatch
syntax enable
filetype plugin indent on

" Load shell base-16 colorscheme
if filereadable(expand("~/.vimrc_background"))
  let base16colorspace=256
  source ~/.vimrc_background
endif














